logging:
  level:
    org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: DEBUG

server:
  shutdown: graceful

spring:
  application:
    name: 'stocks-management-cassandra'
  profiles:
    active:
      - ${SPRING_PROFILE_NAME:dev}
  lifecycle:
    timeout-per-shutdown-phase: 4m
  main:
    banner-mode: off
  mvc:
    converters:
      preferred-json-mapper: jackson
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  spring:
    data:
      cassandra:
        contact-points: ${CASSANDRA_HOSTS:[localhost]}
        port: 9042
        keyspace-name: stocks
        local-datacenter: quotes-datacenter-1
